# Generated by Django 2.2.4 on 2019-08-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
        migrations.AddField(
            model_name='map',
            name='name',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='has_mined',
            field=models.BooleanField(default=False),
        ),
    ]
